repos:
-   repo: https://github.com/psf/black
    rev: 21.6b0
    hooks:
    - id: black
-   repo: https://github.com/PyCQA/flake8
    rev: 3.9.2
    hooks:
    - id: flake8
-   repo: https://github.com/asottile/pyupgrade
    rev: v2.20.0
    hooks:
    - id: pyupgrade
-   repo: https://github.com/nbQA-dev/nbQA
    rev: 0.13.1
    hooks:
    - id: nbqa-black
      additional_dependencies: [black==20.8b1]
    - id: nbqa-pyupgrade
      additional_dependencies: [pyupgrade==2.7.3]
