repos:
-   repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
    - id: black
-   repo: https://github.com/PyCQA/flake8
    rev: 7.1.1
    hooks:
    - id: flake8
-   repo: https://github.com/asottile/pyupgrade
    rev: v3.19.1
    hooks:
    - id: pyupgrade
-   repo: https://github.com/nbQA-dev/nbQA
    rev: 1.9.1
    hooks:
    - id: nbqa-black
      additional_dependencies: [black==20.8b1]
    - id: nbqa-pyupgrade
      additional_dependencies: [pyupgrade==2.7.3]
